
MAX_SPRITES         = 32
MAX_FLYING          = 8
MAX_ITEMS           = 16
MAX_ENEMIES         = 8
MAX_BULLETS         = 64

SHOOT_COOLDOWN      = 25
DEATH_SHOOT_COOLDOWN = 50*2
DEATH_STONE_COOLDOWN = 255

ENEMY_SHOOT_COOLDOWN = 2

LEVEL_Y             = 2
LEVEL_WIDTH         = 32
LEVEL_HEIGHT        = 22

OBJ_PLAYER1_START   = 0
OBJ_PLAYER2_START   = 1
OBJ_PLAYER1_COIN    = 2
OBJ_PLAYER2_COIN    = 3
OBJ_PLAYER1_TOP     = 4
OBJ_PLAYER2_TOP     = 5
OBJ_STONE           = 6
OBJ_GHOST           = 7
OBJ_WEAPON          = 8
OBJ_BAT             = 9
OBJ_FLOWER_LEFT     = 10
OBJ_FLOWER_RIGHT    = 11
OBJ_FLOWER_AUTO     = 12

PASSABLE_ATTR       = 0x47
COIN1_ATTR          = 0x44
COIN2_ATTR          = 0x46
STONE_ATTR          = 0x07
BRICKS_ATTR         = 0x02
BRICKS2_ATTR        = 0x03
BRICKS3_ATTR        = 0x05
BRICKS4_ATTR        = 0x06
BRICKS5_ATTR        = 0x41
STONES1_ATTR        = 0x42
STONES2_ATTR        = 0x43
STONES3_ATTR        = 0x45
STONES4_ATTR        = 0x46
STONES5_ATTR        = 0x41
CHAINS_ATTR         = 0x41  ; passable
WEAPON_ATTR         = 0x45

PHYS_HORIZONTAL     = 0x01
PHYS_LEFT           = 0
PHYS_RIGHT          = 1

PHYS_VERTICAL       = 0x02
PHYS_DOWN           = 0
PHYS_UP             = 2

PHYS_USERDATA       = 0xf0

REASON_ENEMY        = 1
REASON_ITEM         = 2
REASON_BULLET       = 3

ENEMY_RESPAWN_TIME  = 120

KEMPSTON_RIGHT      = 1
KEMPSTON_LEFT       = 2
KEMPSTON_DOWN       = 4
KEMPSTON_UP         = 8
KEMPSTON_FIRE       = 16

Timer               = 0x5C78
